version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/app/chromadb
      - ./.env:/app/.env
    environment:
      - PORT=8000
    restart: unless-stopped
